# Generated by Django 4.2.7 on 2023-11-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CSEC_App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("time", models.TimeField()),
                ("venue", models.CharField(max_length=200)),
                ("organizer", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Events",
            },
        ),
    ]
